# Generated by Django 3.2 on 2021-06-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
