# Generated by Django 3.2 on 2021-06-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0006_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photosallumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pics')),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumni.categories')),
            ],
        ),
    ]
